### ISSUE TITLE
Add documentation to Wiki

### ISSUE THREAD

**Issue by atrnh** [atrnh/Code-Newbie-Tweets#5]
## Todo
- [ ] Docs for the `util` module
- [ ] Docs for the data model
- [ ] Docs for server endpoints
